name = "lily/ecr_template"
version = "0.1.0"
authors = ["lily"]
license = "MIT"

[target]
environment = "roblox"

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
gorp = { wally = "wally#aloroid/gorp-ecr", version = "^0.2.0-rc3" }
vide_snake_case = { name = "alicesaidhi/vide_snake_case", version = "^0.3.1-test.1" }
ecr = { repo = "https://github.com/centau/ecr", rev = "19d1fb4" }

[overrides]
"gorp>ecr" = { repo = "https://github.com/centau/ecr", rev = "19d1fb4" }
